import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";

export interface SessionState {
   city: string;
   unit: string;
   cityList: string[];
   duration: number;
   status: "idle" | "loading" | "failed";
}

const initialState: SessionState = {
   city: "Las Vegas",
   unit: "Fahrenheit",
   status: "idle",
   duration: 0.7,
   cityList: [
      "Abidjan, Côte d'Ivoire",
      "ABU DHABI, United Arab Emirates",
      "Acapulco (de Juárez), Mexico",
      "ACCRA, Ghana",
      "Acheng, China",
      "Ad-Dammam, Saudi Arabia",
      "Adana, Turkey",
      "ADDIS ABABA, Ethiopia",
      "Adelaide, Australia",
      "Agra, India",
      "Aguascalientes, Mexico",
      "Ahmedabad, India",
      "Ahwaz, Iran",
      "Akesu, China",
      "Al-Hasakeh, Syria",
      "Al-Madinah, Saudi Arabia",
      "Al-Rakka, Syria",
      "Aleppo, Syria",
      "Alexandria, Egypt",
      "ALGIERS, Algeria",
      "Aligarh, India",
      "Allahabad, India",
      "Almaty, Kazakhstan",
      "AMMAN, Jordan",
      "Amravati, India",
      "Amritsar, India",
      "AMSTERDAM, Netherlands",
      "Ankang, China",
      "ANKARA, Turkey",
      "Anlu, China",
      "Anqing, China",
      "Anqiu, China",
      "Anshan, China",
      "Anshun, China",
      "Antalya, Turkey",
      "ANTANANARIVO, Madagascar",
      "Anyang, China",
      "Arequipa, Peru",
      "Asansol, India",
      "ASTANA, Kazakhstan",
      "ASUNCION, Paraguay",
      "At-Ta'if, Saudi Arabia",
      "ATHENS, Greece",
      "Atlanta (GA), United States",
      "Auckland, New Zealand",
      "Aurangabad, India",
      "Austin (TX), United States",
      "BAGHDAD, Iraq",
      "BAKU, Azerbaijan",
      "Baltimore (MD), United States",
      "BAMAKO, Mali",
      "Bandar Lampung, Indonesia",
      "Bandjarmasin, Indonesia",
      "Bandung, Indonesia",
      "Bangalore, India",
      "BANGKOK, Thailand",
      "Baoding, China",
      "Baoji, China",
      "Baoshan, China",
      "Baotou, China",
      "Barcelona, Spain",
      "Bareilly, India",
      "Barnaul, Russia",
      "Barquisimeto, Venezuela",
      "Barranquilla, Colombia",
      "Batam, Indonesia",
      "Bazhong, China",
      "Bazhou, China",
      "Beihai, China",
      "BEIJING (PEKING), China",
      "Beiliu, China",
      "Beining, China",
      "Beipiao, China",
      "Belém, Brazil",
      "BELGRADE, Serbia",
      "Belo Horizonte, Brazil",
      "Bengbu, China",
      "BENGHAZI, Libya",
      "Béni-Mellal, Morocco",
      "Benin City, Nigeria",
      "Benxi, China",
      "BERLIN, Germany",
      "Bhilai Nagar, India",
      "Bhiwandi, India",
      "Bhopal, India",
      "Bhubaneswar, India",
      "Bijie, China",
      "Bikaner, India",
      "Binzhou, China",
      "Birmingham[] , United Kingdom",
      "BISHKEK, Kyrgyzstan",
      "Blantyre City, Malawi",
      "Bogor, Indonesia",
      "BOGOTA, Colombia",
      "Bonn, Germany",
      "Boston (MA), United States",
      "Botou, China",
      "Bozhou, China",
      "BRASILIA, Brazil",
      "Bremen, Germany",
      "Brisbane, Australia",
      "Bristol, United Kingdom",
      "BRUSSELS, Belgium",
      "BUCHAREST, Romania",
      "Bucheon (Puchon), South Korea",
      "BUDAPEST, Hungary",
      "BUENOS AIRES, Argentina",
      "Bulawayo, Zimbabwe",
      "Bursa, Turkey",
      "Busan (Pusan), South Korea",
      "CAIRO, Egypt",
      "Calgary, Canada",
      "Cali, Colombia",
      "Callao, Peru",
      "Caloocan, Philippines",
      "Campinas, Brazil",
      "Campo Grande, Brazil",
      "Cancun, Mexico",
      "CAPE TOWN, South Africa",
      "CARACAS, Venezuela",
      "Cartagena, Colombia",
      "Casablanca (Dar-el-Beida), Morocco",
      "Cebu, Philippines",
      "Cenxi, China",
      "Chandigarh, India",
      "Changchun, China",
      "Changde, China",
      "Changge, China",
      "Changle, China",
      "Changning, China",
      "Changsha, China",
      "Changshu, China",
      "Changyi, China",
      "Changzhi, China",
      "Changzhou, China",
      "Chaohu, China",
      "Chaoyang (Guangdong), China",
      "Charlotte (NC), United States",
      "Chelyabinsk, Russia",
      "Chengdu, China",
      "Chenghai, China",
      "Chennai (Madras), India",
      "Chenzhou, China",
      "Cheongju, South Korea",
      "Chiba, Japan",
      "Chicago (IL), United States",
      "Chifeng, China",
      "Chihuahua, Mexico",
      "Chittagong, Bangladesh",
      "Chizhou, China",
      "Chon Buri, Thailand",
      "Chongjin, North Korea",
      "Chongqing, China",
      "Chongzhou, China",
      "Ciudad Guayana, Venezuela",
      "Cixi, China",
      "Cochabamba, Bolivia",
      "Coimbatore, India",
      "Colombo, Brazil",
      "COLOMBO, Sri Lanka",
      "Columbus (OH), United States",
      "CONAKRY, Guinea",
      "Contagem, Brazil",
      "Córdoba, Argentina",
      "Cotonou, Benin",
      "Cúcuta, Colombia",
      "Cuernavaca, Mexico",
      "Cuiabá, Brazil",
      "Culiacán Rosales, Mexico",
      "Curitiba, Brazil",
      "Cuttack, India",
      "Daegu (Taegu), South Korea",
      "Daejeon (Taejon), South Korea",
      "Dafeng, China",
      "DAKAR, Senegal",
      "Dali, China",
      "Dalian, China",
      "Dallas (TX), United States",
      "DAMASCUS, Syria",
      "Dandong, China",
      "Danyang, China",
      "Danzhou, China",
      "Daqing, China",
      "Dar es Salaam, Tanzania",
      "Dashiqiao, China",
      "Datong, China",
      "Davao, Philippines",
      "Daye, China",
      "Dehradun, India",
      "Dehui, China",
      "Deir El-Zor, Syria",
      "Delhi, India",
      "Dengfeng, China",
      "Dengzhou, China",
      "Denver (CO), United States",
      "Detroit (MI), United States",
      "Deyang, China",
      "Dezhou, China",
      "DHAKA, Bangladesh",
      "Dhanbad, India",
      "Dingzhou, China",
      "Diyarbakir, Turkey",
      "Dnipropetrovsk, Ukraine",
      "Donetsk (Donestskaya oblast), Ukraine",
      "Donggang, China",
      "Dongguan, China",
      "Dongtai, China",
      "Dongyang, China",
      "Dongying, China",
      "Dortmund, Germany",
      "Douala, Cameroon",
      "Dubai, United Arab Emirates",
      "DUBLIN, Ireland",
      "Duisburg, Germany",
      "Dujiangyan, China",
      "Duque de Caxias, Brazil",
      "Durban, South Africa",
      "Durg-Bhilai Nagar, India",
      "DUSHANBE, Tajikistan",
      "Düsseldorf, Germany",
      "Edmonton, Canada",
      "Ekaterinoburg, Russia",
      "El Alto, Bolivia",
      "El Paso (TX), United States",
      "El-Jadida, Morocco",
      "Enshi, China",
      "Esfahan, Iran",
      "Essen, Germany",
      "Ezhou, China",
      "Faisalabad (Lyallpur), Pakistan",
      "Faridabad, India",
      "Feicheng, China",
      "Feira de Santana, Brazil",
      "Fengcheng (Jiangxi), China",
      "Fengcheng (Liaoning), China",
      "Fengnan, China",
      "Fès, Morocco",
      "Fort Worth (TX), United States",
      "Fortaleza, Brazil",
      "Foshan, China",
      "Frankfurt am Main, Germany",
      "Fuan, China",
      "Fuding, China",
      "Fukuoka, Japan",
      "Funabashi, Japan",
      "Fuqing, China",
      "Fushun, China",
      "Fuxin, China",
      "Fuyang (Anhui), China",
      "Fuyang (Zhejiang), China",
      "Fuzhou (Fujian), China",
      "Fuzhou (Jiangxi), China",
      "Gaizhou, China",
      "Gaoan, China",
      "Gaobeidian, China",
      "Gaocheng, China",
      "Gaomi, China",
      "Gaoyao, China",
      "Gaoyou, China",
      "Gaozhou, China",
      "Gaziantep, Turkey",
      "Genova, Italy",
      "Ghaziabad, India",
      "Giza, Egypt",
      "Glasgow, United Kingdom",
      "Goiânia, Brazil",
      "Gold Coast-Tweed, Australia",
      "Gongyi, China",
      "Gongzhuling, China",
      "Gorakhpur, India",
      "Göteborg, Sweden",
      "Goyang, South Korea",
      "Guadalajara, Mexico",
      "Guang'an, China",
      "Guanghan, China",
      "Guangshui, China",
      "Guangyuan, China",
      "Guangzhou, China",
      "Guarulhos, Brazil",
      "GUATEMALA CITY, Guatemala",
      "Guayaquil, Ecuador",
      "Guigang, China",
      "Guilin, China",
      "Guiping, China",
      "Guixi, China",
      "Guiyang, China",
      "Gujranwala, Pakistan",
      "Guwahati, India",
      "Gwalior, India",
      "Gwangju (Kwangchu), South Korea",
      "Hà Noi (HANOI), Viet Nam",
      "Hachioji, Japan",
      "Haicheng, China",
      "Haikou, China",
      "Hailun, China",
      "Haimen, China",
      "Haining, China",
      "Haiphong, Viet Nam",
      "Haiyang, China",
      "Hama, Syria",
      "Hamamatsu, Japan",
      "Hamburg, Germany",
      "Hamhung, North Korea",
      "Hamilton, Canada",
      "Hanchuan, China",
      "Handan, China",
      "Hangzhou (Hangchow) , China",
      "Haora (Howrah), India",
      "HARARE, Zimbabwe",
      "Harbin (Haerbin), China",
      "HAVANA, Cuba",
      "Hechuan, China",
      "Hefei, China",
      "Hegang, China",
      "Hejian, China",
      "HELSINKI, Finland",
      "Hengyang, China",
      "Hermosillo, Mexico",
      "Heze, China",
      "Hezhou, China",
      "Hiroshima, Japan",
      "Ho Chi Minh City (Saigon), Viet Nam",
      "Homs, Syria",
      "HONG KONG, China - Hong Kong",
      "Honghu, China",
      "Houston (TX), United States",
      "Huaian, China",
      "Huaibei, China",
      "Huainan, China",
      "Huaiyin, China",
      "Huangshi (Hubei), China",
      "Huazhou, China",
      "Hubli-Dharwad, India",
      "Huhehaote, China",
      "Huixian, China",
      "Huiyang, China",
      "Huizhou, China",
      "Huludao, China",
      "Huzhou, China",
      "Hyderabad, India",
      "Hyderabad, Pakistan",
      "Ibadan, Nigeria",
      "Içel, Turkey",
      "Ilorin, Nigeria",
      "Imbaba, Egypt",
      "Incheon, South Korea",
      "Indianapolis (IN), United States",
      "Indore, India",
      "Irkutsk, Russia",
      "ISLAMABAD, Pakistan",
      "Istanbul, Turkey",
      "Izhevsk, Russia",
      "Izmir, Turkey",
      "Jabalpur, India",
      "Jaboatao dos Guarapes, Brazil",
      "Jacksonville (FL), United States",
      "Jaipur, India",
      "JAKARTA, Indonesia",
      "Jalandhar, India",
      "Jammu, India",
      "Jamnagar, India",
      "Jamshedpur, India",
      "Jeddah (Jiddah), Saudi Arabia",
      "Jeonju (Chonchu), South Korea",
      "JERUSALEM, Israel",
      "Ji'nan, China",
      "Jiamusi, China",
      "Jiangdu, China",
      "Jiangjin, China",
      "Jiangmen, China",
      "Jiangyan, China",
      "Jiangyin, China",
      "Jiangyou, China",
      "Jianyang (Sichuan), China",
      "Jiaonan, China",
      "Jiaozhou, China",
      "Jiaozuo, China",
      "Jiaxing, China",
      "Jieshou, China",
      "Jieyang, China",
      "Jilin, China",
      "Jimo, China",
      "Jingjiang, China",
      "Jingmen, China",
      "Jingzhou, China",
      "Jining (Shandong), China",
      "Jinjiang, China",
      "Jintan, China",
      "Jinzhong, China",
      "Jinzhou (Hebei), China",
      "Jinzhou (Liaoning), China",
      "Jiujiang, China",
      "Jiutai, China",
      "Jixi, China",
      "Jiyuan, China",
      "Joao Pessoa, Brazil",
      "Jodhpur, India",
      "Johannesburg, South Africa",
      "Juárez, Mexico",
      "Jurong, China",
      "KABUL, Afghanistan",
      "Kadhimain, Iraq",
      "Kaduna, Nigeria",
      "Kagoshima, Japan",
      "Kaifeng, China",
      "Kaiping, China",
      "Kaiyuan (Liaoning), China",
      "Kalookan (Caloocan), Philippines",
      "Kalyan, India",
      "KAMPALA, Uganda",
      "Kano, Nigeria",
      "Kanpur, India",
      "Kaohsiung, China",
      "Karachi, Pakistan",
      "Karaj, Iran",
      "KATHMANDU, Nepal",
      "Katowice, Poland",
      "Kawasaki, Japan",
      "Kayes, Mali",
      "Kayseri, Turkey",
      "Kazan, Russia",
      "Kemerovo, Russia",
      "Kénitra, Morocco",
      "Kerman, Iran",
      "Kermanshah, Iran",
      "Khabarovsk, Russia",
      "Kharkiv, Ukraine",
      "Khartoum North, Sudan",
      "KHARTOUM, Sudan",
      "Khulna, Bangladesh",
      "KINGSTON, Jamaica",
      "KINSHASA, Dem Rep of Congo",
      "KISHINEV, Moldova",
      "Kisumu, Kenya",
      "Kitakyushu, Japan",
      "Kobe, Japan",
      "Kochi, India",
      "Kolkata (Calcutta), India",
      "Köln, Germany",
      "Konya, Turkey",
      "Kota, India",
      "Koulikoro, Mali",
      "Kozhikode, India",
      "Kraków, Poland",
      "Krasnodar, Russia",
      "Krasnoyarsk, Russia",
      "Kryviy Rig, Ukraine",
      "KUALA LUMPUR, Malaysia",
      "Kumamoto, Japan",
      "Kumasi, Ghana",
      "Kunming, China",
      "Kunshan, China",
      "KYIV (KIEV), Ukraine",
      "Kyoto, Japan",
      "La Matanza, Argentina",
      "LA PAZ, Bolivia",
      "La Plata, Argentina",
      "Lagos, Nigeria",
      "Lahore, Pakistan",
      "Laiwu, China",
      "Laixi, China",
      "Laiyang, China",
      "Laizhou, China",
      "Langfang, China",
      "Langzhong, China",
      "Lanxi, China",
      "Lanzhou, China",
      "Las Vegas (NV), United States",
      "Lattakia, Syria",
      "Leiyang, China",
      "Leizhou, China",
      "Leling, China",
      "León (de los Aldama), Mexico",
      "Leping, China",
      "Leqing, China",
      "Leshan, China",
      "Lianjiang, China",
      "Lianyuan, China",
      "Lianyungang, China",
      "Liaocheng, China",
      "Liaoyang, China",
      "Lichuan, China",
      "Liling, China",
      "LILONGWE, Malawi",
      "LIMA, Peru",
      "Linfen, China",
      "Lingbao, China",
      "Linghai, China",
      "Lingyuan, China",
      "Linhai, China",
      "Linqing, China",
      "Linyi, China",
      "Linzhou, China",
      "LISBON, Portugal",
      "Liuan, China",
      "Liupanshui, China",
      "Liuyang, China",
      "Liuzhou, China",
      "Liverpool, United Kingdom",
      "Liyang, China",
      "Lódz, Poland",
      "Lomas de Zamora, Argentina",
      "LONDON, United Kingdom",
      "Longhai, China",
      "Longkou, China",
      "Longyan, China",
      "Los Angeles (CA), United States",
      "Louisville (KY), United States",
      "LUANDA, Angola",
      "Lucknow, India",
      "Ludhiana, India",
      "Lufeng, China",
      "Luoding, China",
      "Luoyang, China",
      "LUSAKA, Zambia",
      "Luzhou, China",
      "Lviv, Ukraine",
      "Maanshan, China",
      "Maceió, Brazil",
      "Macheng, China",
      "MADRID, Spain",
      "Madurai, India",
      "Maiduguri, Nigeria",
      "Makasar (Ujung Pandang), Indonesia",
      "Makhachkala, Russia",
      "Makkah, Saudi Arabia",
      "Málaga, Spain",
      "Malang, Indonesia",
      "Malmö, Sweden",
      "MANAGUA, Nicaragua",
      "Manaus, Brazil",
      "Manchester, United Kingdom",
      "Mangalore, India",
      "MANILA, Philippines",
      "Maoming, China",
      "MAPUTO, Mozambique",
      "Maracaibo, Venezuela",
      "Marrakech, Morocco",
      "Marseille, France",
      "Mashhad, Iran",
      "Medan, Indonesia",
      "Medellín, Colombia",
      "Meerut, India",
      "Meihekou, China",
      "Meishan, China",
      "Meknès, Morocco",
      "Melbourne, Australia",
      "Memphis (TN), United States",
      "Mendoza, Argentina",
      "Mérida, Mexico",
      "Mexicali, Mexico",
      "MEXICO CITY, Mexico",
      "Miami (FL), United States",
      "Mianyang, China",
      "Milan (Milano), Italy",
      "Miluo, China",
      "Milwaukee (WI), United States",
      "Mingguang, China",
      "Minneapolis (MN), United States",
      "MINSK, Belarus",
      "Mira-Bhayandar, India",
      "MOGADISHU, Somalia",
      "Mombasa, Kenya",
      "Monterrey, Mexico",
      "MONTEVIDEO, Uruguay",
      "Montréal, Canada",
      "Mopti, Mali",
      "Moradabad, India",
      "Morelia, Mexico",
      "Morón, Argentina",
      "MOSCOW, Russia",
      "Mosul, Iraq",
      "Mudanjiang, China",
      "Multan, Pakistan",
      "Mumbai (Bombay), India",
      "München, Germany",
      "Mysore, India",
      "N'DJAMENA, Chad",
      "Nagoya, Japan",
      "Nagpur, India",
      "NAIROBI, Kenya",
      "Nakhon Ratchasima, Thailand",
      "Nakuru, Kenya",
      "Nampho, North Korea",
      "Nan'an, China",
      "Nanchang, China",
      "Nanchong, China",
      "Nanchuan, China",
      "Nanhai, China",
      "Nanjing (Nanking) , China",
      "Nankang, China",
      "Nanning, China",
      "Nantong, China",
      "Nanyang, China",
      "Naples (Napoli), Italy",
      "Nashik, India",
      "Nashville-Davidson (TN), United States",
      "Natal, Brazil",
      "Navi Mumbai (New Bombay), India",
      "Nehe, China",
      "Neijiang, China",
      "New York (NY), United States",
      "NIAMEY, Niger",
      "Niigata, Japan",
      "Ningbo, China",
      "Nizhny Novgorod, Russia",
      "Nonthaburi, Thailand",
      "Nottingham, United Kingdom",
      "NOUAKCHOTT, Mauritania",
      "Nova Iguaçu, Brazil",
      "Novokuznetsk, Russia",
      "Novosibirsk, Russia",
      "Odessa, Ukraine",
      "Okayama, Japan",
      "Oklahoma City (OK), United States",
      "Omdurman, Sudan",
      "Omsk, Russia",
      "Oran (Wahran), Algeria",
      "Orenburg, Russia",
      "Orumiyeh, Iran",
      "Osaka, Japan",
      "Osasco, Brazil",
      "OSLO, Norway",
      "OTTAWA, Canada",
      "OUAGADOUGOU, Burkina Faso",
      "Padang, Indonesia",
      "Pakanbaru, Indonesia",
      "Palembang, Indonesia",
      "Palermo, Italy",
      "Panjin, China",
      "Panshi, China",
      "Panzhihua, China",
      "PARIS, France",
      "Patna, India",
      "Pengzhou, China",
      "Perm, Russia",
      "Perth, Australia",
      "Peshawar, Pakistan",
      "Philadelphia (PA), United States",
      "PHNOM PENH, Cambodia",
      "Phoenix (AZ), United States",
      "Pikine-Guediawaye, Senegal",
      "Pimpri Chinchwad, India",
      "Pingdingshan, China",
      "Pingdu, China",
      "Pingxiang (Jiangxi), China",
      "Pizhou, China",
      "Port Elizabeth, South Africa",
      "Port Harcourt, Nigeria",
      "PORT-AU-PRINCE, Haiti",
      "Portland (OR), United States",
      "Porto Alegre, Brazil",
      "Poznan, Poland",
      "PRAGUE, Czech Republic",
      "Preston, United Kingdom",
      "PRETORIA, South Africa",
      "Puebla de Zaragoza, Mexico",
      "Puente Alto, Chile",
      "Pulandian, China",
      "Pune, India",
      "Puning, China",
      "PYONGYANG, North Korea",
      "Qian'an, China",
      "Qianjiang, China",
      "Qidong, China",
      "Qingdao (Tsingtao) , China",
      "Qingzhou, China",
      "Qinhuangdao, China",
      "Qinzhou, China",
      "Qionglai, China",
      "Qiongshan, China",
      "Qiqihaer, China",
      "Qixia, China",
      "Qom, Iran",
      "Quanzhou, China",
      "Québec, Canada",
      "Querétaro, Mexico",
      "Quetta, Pakistan",
      "Quezon City, Philippines",
      "Qufu, China",
      "QUITO, Ecuador",
      "Qujing, China",
      "RABAT, Morocco",
      "Raipur, India",
      "Rajkot, India",
      "Ranchi, India",
      "Rasht, Iran",
      "Rawalpindi, Pakistan",
      "Recife, Brazil",
      "Renhuai, China",
      "Renqiu, China",
      "Reynosa, Mexico",
      "Ribeirao Prêto, Brazil",
      "RIGA, Latvia",
      "Rio de Janeiro, Brazil",
      "RIYADH, Saudi Arabia",
      "Rizhao, China",
      "ROME, Italy",
      "Rongcheng, China",
      "Rosario, Argentina",
      "Rostov-na-Donu, Russia",
      "Rotterdam, Netherlands",
      "Rugao, China",
      "Ruian, China",
      "Ruijin, China",
      "Rushan, China",
      "Ruzhou, China",
      "Safi, Morocco",
      "Sagamihara, Japan",
      "Saint Petersburg (Leningrad), Russia",
      "Saitama, Japan",
      "Sakai, Japan",
      "Salé, Morocco",
      "Salem, India",
      "Saltillo, Mexico",
      "Salvador, Brazil",
      "Samara (Samarskaya oblast), Russia",
      "Samarinda, Indonesia",
      "Samut Prakan, Thailand",
      "San Antonio (TX), United States",
      "San Diego (CA), United States",
      "San Francisco (CA), United States",
      "San Jose (CA), United States",
      "San Juan, Philippines",
      "San Luis Potosí, Mexico",
      "San Miguel de Tucumán, Argentina",
      "SANA'A, Yemen",
      "Santa Cruz, Bolivia",
      "Santiago de los Caballeros, Dominican Republic",
      "SANTIAGO, Chile",
      "Santo André, Brazil",
      "SANTO DOMINGO, Dominican Republic",
      "Sao Bernardo do Campo, Brazil",
      "Sao Gonçalo, Brazil",
      "Sao José dos Campos, Brazil",
      "Sao Luís, Brazil",
      "Sao Paulo, Brazil",
      "Sapporo, Japan",
      "SARAJEVO, Bosnia and Herzegovina",
      "Saratov, Russia",
      "Seattle (WA), United States",
      "Ségou, Mali",
      "Semarang, Indonesia",
      "Sendai, Japan",
      "Seongnam, South Korea",
      "SEOUL, South Korea",
      "Sevilla, Spain",
      "Shanghai, China",
      "Shangqiu, China",
      "Shangyu, China",
      "Shangzhi, China",
      "Shangzhou, China",
      "Shantou, China",
      "Shaoguan, China",
      "Shaoxing, China",
      "Shaoyang, China",
      "Sheffield, United Kingdom",
      "Shengzhou, China",
      "Shenyang, China",
      "Shenzhen, China",
      "Shenzhou, China",
      "Shihezi, China",
      "Shijiazhuang, China",
      "Shimkent, Kazakhstan",
      "Shiraz, Iran",
      "Shishou, China",
      "Shiyan, China",
      "Shizuoka, Japan",
      "Shouguang, China",
      "Shuangcheng, China",
      "Shubra-El-Khema, Egypt",
      "Shulan, China",
      "Shunde, China",
      "Shuozhou, China",
      "Sikasso, Mali",
      "SINGAPORE, Singapore",
      "SKOPLJE, Macedonia",
      "SOFIA, Bulgaria",
      "Solapur, India",
      "Songyuan, China",
      "Songzi, China",
      "Sorocaba, Brazil",
      "Soweto, South Africa",
      "Srinagar, India",
      "St. Louis (MO), United States",
      "STOCKHOLM, Sweden",
      "Stuttgart, Germany",
      "Suihua, China",
      "Suining, China",
      "Suizhou, China",
      "Surabaya, Indonesia",
      "Surat, India",
      "Suwon (Puwan), South Korea",
      "Suzhou (Anhui), China",
      "Suzhou (Jiangsu), China",
      "Sydney, Australia",
      "Tabriz, Iran",
      "Taian, China",
      "Taichung, China",
      "Tainan, China",
      "Taipei, Taiwan (China ROC)",
      "Taishan, China",
      "Taixing, China",
      "Taiyuan, China",
      "Taizhou (Jiangsu), China",
      "Taizhou (Zhejiang), China",
      "Tampa (FL), United States",
      "Tampico, Mexico",
      "Tanger, Morocco",
      "Tangerang, Indonesia",
      "Tangshan, China",
      "TASHKENT, Uzbekistan",
      "TBILISI, Georgia",
      "TEGUCIGALPA, Honduras",
      "TEHRAN, Iran",
      "Tel Aviv-Yafo, Israel",
      "Tengzhou, China",
      "Teresina, Brazil",
      "Tétouan, Morocco",
      "Thane, India",
      "The Hague, Netherlands",
      "Thiruvananthapuram, India",
      "Tianchang, China",
      "Tianjin (Tientsin), China",
      "Tianmen, China",
      "Tianshui, China",
      "Tijuana, Mexico",
      "Tiruchchirappalli, India",
      "Tiruppur, India",
      "TOKYO, Japan",
      "Toluca (de Lerdo), Mexico",
      "Tolyatti, Russia",
      "Tongcheng, China",
      "Tongliao, China",
      "Tongxiang, China",
      "Tongzhou, China",
      "Torino, Italy",
      "Toronto, Canada",
      "Torreón, Mexico",
      "TRIPOLI, Libya",
      "Trujillo, Peru",
      "TUNIS, Tunisia",
      "Tyneside, United Kingdom",
      "Tyumen, Russia",
      "Uberlândia, Brazil",
      "Ufa, Russia",
      "ULAANBAATAR, Mongolia",
      "Ulsan, South Korea",
      "Ulyanovsk, Russia",
      "Urumqi, China",
      "Vadodara, India",
      "Valencia, Spain",
      "Valencia, Venezuela",
      "Vancouver, Canada",
      "Varanasi, India",
      "Veracruz, Mexico",
      "VIENNA, Austria",
      "VIENTIANE, Laos",
      "Vijayawada, India",
      "VILNIUS, Lithuania",
      "Visakhapatnam, India",
      "Vladivostok, Russia",
      "Volgograd, Russia",
      "Voronezh, Russia",
      "Wafangdian, China",
      "Wanyuan, China",
      "Warangal, India",
      "WARSAW, Poland",
      "WASHINGTON (DC), United States",
      "Weifang, China",
      "Weihai, China",
      "Weinan, China",
      "Wendeng, China",
      "Wenling, China",
      "Wenzhou, China",
      "West Midlands, United Kingdom",
      "West Yorkshire, United Kingdom",
      "Winnipeg, Canada",
      "Wroclaw, Poland",
      "Wuan, China",
      "Wuchang, China",
      "Wuchuan, China",
      "Wugang (Hunan), China",
      "Wuhan, China",
      "Wuhu, China",
      "Wujiang, China",
      "Wujin, China",
      "Wuwei, China",
      "Wuxi, China",
      "Wuxian, China",
      "Wuxue, China",
      "Xi'an (Sian) , China",
      "Xi'ning, China",
      "Xiamen, China",
      "Xiangcheng, China",
      "Xiangfan, China",
      "Xiangtan, China",
      "Xiangxiang, China",
      "Xianning, China",
      "Xiantao, China",
      "Xianyang, China",
      "Xiaogan, China",
      "Xiaoshan, China",
      "Xichang, China",
      "Xingcheng, China",
      "Xinghua, China",
      "Xingning, China",
      "Xingping, China",
      "Xingtai, China",
      "Xingyang, China",
      "Xingyi, China",
      "Xinhui, China",
      "Xinji, China",
      "Xinmi, China",
      "Xinmin, China",
      "Xintai, China",
      "Xinxiang, China",
      "Xinyang, China",
      "Xinyi (Guangdong), China",
      "Xinyi (Jiangsu), China",
      "Xinyu, China",
      "Xinzheng, China",
      "Xishan, China",
      "Xuancheng, China",
      "Xuanwei, China",
      "Xuzhou, China",
      "Yancheng, China",
      "Yangchun, China",
      "Yangjiang, China",
      "Yangon , Myanmar",
      "Yangquan, China",
      "Yangzhou, China",
      "Yanshi, China",
      "Yantai, China",
      "YAOUNDE, Cameroon",
      "Yaroslave, Russia",
      "YEREVAN, Armenia",
      "Yibin, China",
      "Yichang, China",
      "Yicheng, China",
      "Yichun (Heilongjiang), China",
      "Yichun (Jiangxi), China",
      "Yinchuan, China",
      "Yingcheng, China",
      "Yingde, China",
      "Yingkou, China",
      "Yiwu, China",
      "Yixing, China",
      "Yiyang, China",
      "Yizheng, China",
      "Yizhou, China",
      "Yokohama, Japan",
      "Yongcheng, China",
      "Yongchuan, China",
      "Yongkang, China",
      "Yongzhou, China",
      "Yuanjiang, China",
      "Yueyang, China",
      "Yuhang, China",
      "Yulin (Guangxi), China",
      "Yuncheng, China",
      "Yunzhou, China",
      "Yushu, China",
      "Yuyao, China",
      "Yuzhou, China",
      "ZAGREB, Croatia",
      "Zahedan, Iran",
      "Zamboanga, Philippines",
      "Zaoyang, China",
      "Zaozhuang, China",
      "Zaporizhya, Ukraine",
      "Zaragoza, Spain",
      "Zaria, Nigeria",
      "Zengcheng, China",
      "Zhangjiagang, China",
      "Zhangjiakou, China",
      "Zhangqiu, China",
      "Zhangshu, China",
      "Zhangzhou, China",
      "Zhanjiang, China",
      "Zhaodong, China",
      "Zhaotong, China",
      "Zhaoyuan, China",
      "Zhengzhou, China",
      "Zhenjiang, China",
      "Zhongshan, China",
      "Zhongxiang, China",
      "Zhoushan, China",
      "Zhuanghe, China",
      "Zhucheng, China",
      "Zhuhai, China",
      "Zhuji, China",
      "Zhuozhou, China",
      "Zhuzhou, China",
      "Zibo, China",
      "Zigong, China",
      "Ziyang, China",
      "Zoucheng, China",
      "Zunhua, China",
      "Zunyi, China",
      "Zürich, Switzerland",
   ],
};

export const sessionSlice = createSlice({
   name: "session",
   initialState,
   // The `reducers` field lets us define reducers and generate associated actions
   reducers: {
      updateSession: (state, action: PayloadAction<any>) => {
         const { city, unit } = action.payload;
         state.city = city;
         state.unit = unit;
      },
      resetSession: () => initialState,
   },
});

export const { updateSession, resetSession } = sessionSlice.actions;
export const selectSession = (state: RootState) => state.session;

export default sessionSlice.reducer;
